### ISSUE TITLE
Framework L-System

### ISSUE THREAD

**Issue by maximdomentii** [maximdomentii/mps-project-2#4]
Am adaugat un direcotr [dev](https://github.com/maximdomentii/mps-project-2/tree/master/dev) care contine un proiect Intellij cu o sursa java ce reprezinta un framework pentru generarea de imagini conform cu L-System. Acest framework dispune de o interfata grafica si o serie de gramatici predefinite conform carora se genereaza niste imagini.

Ceea ce trebuie noi sa facem este:

1. De modificat interfata grafica ca sa nu mai aiba acele gramatici predefinite ci sa genereze ceea ce ne dorim noi in doua moduri:
 - randare la fiecare iteratie astfel incat sa rezulte o animatie
 - randare la final generandu-se astfel doar imaginea finala

2. Modificarea functionalitatii frameworkului astfel incat sa se genereze ori o padure de copaci diferiti si eventual un copac "principal" in prim plan, ori cateva artificii dupa cum am mai discutat.
La momentul de fata frameworkul genereaza o singura imagine pe care o pozitioneaza "undeva" in ecran. Noi va trebui sa generam mai multe astfel de imagini pe care sa le pozitionam la diferite pozitii astfel incat sa rezulte o padure de copaci sau cateva artificii. De exemplu putem avea 10 gramatici care genereaza copaci diferiti din care se selecteaza random una pentru o pozitie random din ecran.

**Comment by nedevl** [comment]
Am gasit o modalitate mult mai simpla de a avea un proiect 100% functional si de succes.

**Comment by vladspartan** [comment]
O sa folosim JS, iar fractalul de la care plecam este tulpina copacului
