### ISSUE TITLE
Documentatie

### ISSUE THREAD

**Issue by maximdomentii** [maximdomentii/mps-project-2#6]
- Lipsa lista taskuri si responsabilitati
- Lipsa GANTT
- Lipsa schema arhitecturala

**Comment by aciortea** [comment]
Ceva update-uri? Inca nu vad documentele.

**Comment by aciortea** [comment]
Notele pentru impresie si termene documentatie o sa apara maine seara (). Pentru ca o echipa Crispy Team a avut documentatia completa data trecuta la termene documentatie aveti momentan -0.5

**Comment by nedevl** [comment]
@aciortea Accept me as a friend on Fb.

**Comment by maximdomentii** [comment]
> Lipsa lista taskuri si responsabilitati

Done by @maximdomentii

**Comment by maximdomentii** [comment]
> Lipsa GANTT
> Lipsa schema arhitecturala

Done by @rvlad-patrascu
