### ISSUE TITLE
Echipa este formata din 4?

### ISSUE THREAD

**Issue by aciortea** [maximdomentii/mps-project-2#7]
Hello,

S-a schimbat ceva in componenta echipei?
In readme apar 4 :
Cimpian Vlad - Andrei   342C5   vladcimpian@gmail.com
Domentii Maxim          342C5   domentiimaxim@yahoo.com
Nedeloiu Adrian George  342C5   nedeloiuadrian@gmail.com
Tudureanu Romeo         342C5   romeo.tudureanu@gmail.com

**Comment by nedevl** [comment]
A fost o problema in README.

**Comment by nedevl** [comment]
Why reopened?

On Thursday, 14 January 2016, aciortea <notifications@github.com> wrote:

> Reopened #7 <https://github.com/maximdomentii/mps-project-2/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maximdomentii/mps-project-2/issues/7#event-514300069>.
>


-- 


*______________________________________________________________________George
Adrian Nedeloiu*

*Tel: 0040-729-008460*

*E-Mail: nedeloiuadrian@gmail.com <nedeloiuadrian@gmail.com>*

**Comment by aciortea** [comment]
Este posibil ca echipa sa mai creasca? Sau va opriti la 5?

**Comment by aciortea** [comment]
Spataru Eleonara v-a parasit sau este si ea in echipa cu voi?
